### PR TITLE
Update equality and hash methods of the 'Rule' class

### PR DESCRIPTION
**Pull request by DrMatters**
I'm not sure I ran tests correctly, hope CI does it

### CODE REVIEW

**Comment by DrMatters** [comment]
I suggest updates should be also applied to other classes with '__eq__' and '__hash__' method

**Comment by tommyod** [comment]
Can you explain _why_ this is needed? What problem does it solve compared to the existing code?

**Comment by DrMatters** [comment]
This allows running set-based methods like finding intersections and
subtraction.
Best,
Kirill Semin

**Comment by tommyod** [comment]
Can you explain in more detail, and with a code example? I don't understand.

**Comment by DrMatters** [comment]
This should allow finding common rules:
`
itemsets_1, rules_1 = apriori(transactions=trans_1,)
itemsets_2 rules_2 = apriori(transactions=trans_2,)
common_rules = set(rules_1).intersection(set(rules2))
`

**Comment by tommyod** [comment]
I'm closing this PR. 

The proposed code (once I cleaned up the syntax errors) already works on master:
```python
from efficient_apriori import apriori

transactions = [('eggs', 'bacon', 'soup'), 
                ('eggs', 'bacon', 'soup'), 
                ('eggs', 'bacon', 'soup'),
                ('eggs', 'bacon', 'apple'),
                ('soup', 'bacon', 'banana')]
itemsets_1, rules_1 = apriori(transactions=transactions,)
itemsets_2, rules_2 = apriori(transactions=transactions,)  
common_rules = set(rules_1).intersection(set(rules_2))
```
Since the above works, I don't see what this PR adds. I will gladly re-open if it's explained to me so I can see the value.

**Pull request closed without merging**
